# Generated by Django 4.1.1 on 2022-09-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personal", "0003_alter_contactmessage_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="auth_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.TextField()),
            ],
        ),
    ]
