# Generated by Django 4.1.1 on 2022-09-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Personal", "0004_auth_user"),
    ]

    operations = [
        migrations.DeleteModel(name="auth_user",),
    ]
