# Generated by Django 4.1.1 on 2022-09-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personal", "0012_alter_memberimages_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/project")),
                ("topic", models.CharField(max_length=200)),
                ("text", models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name="memberimages",
            name="image",
            field=models.ImageField(upload_to="images/member"),
        ),
    ]
