# Generated by Django 4.1.1 on 2022-09-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personal", "0013_project1_alter_memberimages_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project1",
            name="file",
            field=models.FileField(blank=True, upload_to="documents/"),
        ),
    ]
