# Generated by Django 4.1.2 on 2022-10-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personal", "0014_project1_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("Student_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=250)),
            ],
        ),
    ]
