# Generated by Django 4.1.2 on 2022-10-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Personal", "0017_alter_auth_user_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auth_user", old_name="gender", new_name="is_gender",
        ),
    ]
