# Generated by Django 4.1.2 on 2022-10-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personal", "0029_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="username", name="age", field=models.IntegerField(max_length=2),
        ),
    ]
