# Generated by Django 4.1 on 2022-09-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personal", "0002_auto_20220914_0009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
