# Generated by Django 4.1.2 on 2022-10-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personal", "0016_auth_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auth_user",
            name="gender",
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
