# Generated by Django 4.1.2 on 2022-10-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("Personal", "0018_rename_gender_auth_user_is_gender"),
    ]

    operations = [
        migrations.RenameModel(old_name="Auth_user", new_name="CustomUser",),
    ]
