# Generated by Django 4.1.2 on 2022-10-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("Personal", "0019_rename_auth_user_customuser"),
    ]

    operations = [
        migrations.RenameModel(old_name="CustomUser", new_name="Auth_user",),
    ]
