# Generated by Django 4.1.2 on 2022-10-07 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Personal", "0021_myappuser_delete_auth_user"),
    ]

    operations = [
        migrations.DeleteModel(name="MyappUser",),
    ]
