# Generated by Django 4.1.2 on 2022-10-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personal", "0028_delete_auth_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="username",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("gender", models.CharField(max_length=200)),
                ("age", models.IntegerField(max_length=200)),
            ],
        ),
    ]
