# Generated by Django 4.1 on 2022-10-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personal", "0030_alter_username_age"),
    ]

    operations = [
        migrations.RemoveField(model_name="memberimages", name="text",),
        migrations.AddField(
            model_name="memberimages",
            name="ability",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="memberimages",
            name="community",
            field=models.URLField(blank=True, db_index=True, unique=True),
        ),
        migrations.AddField(
            model_name="memberimages",
            name="github",
            field=models.URLField(blank=True, db_index=True, unique=True),
        ),
        migrations.AddField(
            model_name="memberimages",
            name="workexperience",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="memberimages",
            name="year",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="memberimages",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
