# Generated by Django 4.1 on 2022-10-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Personal", "0031_remove_memberimages_text_memberimages_ability_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="memberimages", name="community",),
        migrations.RemoveField(model_name="memberimages", name="github",),
    ]
