# Generated by Django 3.2.8 on 2022-10-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0032_remove_memberimages_community_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/index')),
                ('topic', models.CharField(max_length=254)),
            ],
        ),
    ]
